version: '3.8'

services:
  bot-api:
    build:
      context: ./bot
      dockerfile: Bot.Api/Dockerfile
    ports:
      - "5001:80"
    networks:
      - botnet-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  ccs-api:
    build:
      context: ./ccs
      dockerfile: commandcontrolserver.api/Dockerfile
    ports:
      - "5002:80"
    networks:
      - botnet-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  ccs-frontend:
    build:
      context: ./ccs
      dockerfile: commandcontrolserver-frontend/Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - ccs-api
    networks:
      - botnet-network

networks:
  botnet-network:
    driver: bridge
