name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore and Build
      working-directory: BotNet/bot/Bot.Api
      run: |
        dotnet restore
        dotnet build --configuration Release --no-restore

    - name: Run Unit Tests
      working-directory: BotNet/bot/Bot.Api
      run: dotnet test --no-build --verbosity normal
